In [1]:
import numpy as np
import math

In [2]:
nIn = 14
ratio = 0.7
poolSize = 2
nOut = int(math.floor(nIn*ratio))
alpha = (nIn - poolSize)/float(nOut - 1)
u = 0.5
print("Size of input/output = {%d,%d} with ratio of %f, alpha = %f, u = %f and pooling region size of %d." % (nIn,nOut,ratio,alpha,u,poolSize))

Size of input/output = {14,9} with ratio of 0.700000, alpha = 1.500000, u = 0.500000 and pooling region size of 2.


In [25]:
sequences = np.empty((nOut)).astype(np.int32)
for i in xrange(sequences.size):
    if i == 0:
        sequences[i] = 0
    elif i == sequences.size-1:
        sequences[i] = nIn - 2
    else:
        sequences[i] = int(math.ceil(alpha*(i+u))) - 1


In [26]:
print("Pseudo random sequence")
print(sequences)
for i in xrange(1,sequences.size+1):
    print("Pooling region %d ==> from %d, to %d " %(i,sequences[i-1],sequences[i-1]+poolSize-1))

Pseudo random sequence
[ 0  2  3  5  6  8  9 11 12]
Pooling region 1 ==> from 0, to 1 
Pooling region 2 ==> from 2, to 3 
Pooling region 3 ==> from 3, to 4 
Pooling region 4 ==> from 5, to 6 
Pooling region 5 ==> from 6, to 7 
Pooling region 6 ==> from 8, to 9 
Pooling region 7 ==> from 9, to 10 
Pooling region 8 ==> from 11, to 12 
Pooling region 9 ==> from 12, to 13 


In [28]:
x,y  = np.random.randint(0,100,nIn), np.empty((nOut)).astype(np.int32)
print("Input and output before forward pass")
print(np.arange(nIn))
print(x)
print(sequences)
print(y)

Input and output before forward pass
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 1 41 92 53 26 78 83 96 64 84 98 23 51  8]
[ 0  2  3  5  6  8  9 11 12]
[0 0 0 0 0 0 0 0 0]


In [34]:
for i in xrange(y.size):
    idx = sequences[i]
    print("Pooling region number %i starting at %d" % (i,idx))
    maxVal = -1e10
    for j in xrange(poolSize):
        idxj = int(idx+j)
        val = x[idxj]
        if val > maxVal:
            maxVal = val
    
        print(idxj,val)
    y[i] = maxVal
    print("Max val = %f",maxVal)
print("Output ==>")
print(y)

Pooling region number 0 starting at 0
(0, 1)
(1, 41)
('Max val = %f', 41)
Pooling region number 1 starting at 2
(2, 92)
(3, 53)
('Max val = %f', 92)
Pooling region number 2 starting at 3
(3, 53)
(4, 26)
('Max val = %f', 53)
Pooling region number 3 starting at 5
(5, 78)
(6, 83)
('Max val = %f', 83)
Pooling region number 4 starting at 6
(6, 83)
(7, 96)
('Max val = %f', 96)
Pooling region number 5 starting at 8
(8, 64)
(9, 84)
('Max val = %f', 84)
Pooling region number 6 starting at 9
(9, 84)
(10, 98)
('Max val = %f', 98)
Pooling region number 7 starting at 11
(11, 23)
(12, 51)
('Max val = %f', 51)
Pooling region number 8 starting at 12
(12, 51)
(13, 8)
('Max val = %f', 51)
Output ==>
[41 92 53 83 96 84 98 51 51]
